♻️ Sequencing experiment field refactor
kids-first/kf-api-dataservice pull request #477
Opened 2018-11-16 16:07 UTC by dankolbman

2018-11-16 17:09 UTC, znatty22 reviewed
Looks good so far. Are you going to add the migration script as well?

2018-11-16 17:09 UTC, znatty22 commented on dataservice/api/genomic_file/README.md
> +Most all `Genomic Files` should be able to resolve to one or more `Biospecimens`
I think this last sentence is a little confusing. Don't all of our unharmonized and harmonized genomic files have links to a Biospecimen through the BiospecimenGenomicFile relation? Maybe its more like, most genomic files should be able to resolve to one or more specimens through the BiospecimenGenomicFile, and others can be resolved using the Task table. And then maybe add something about Task - Task is an executed bioinformatic process which produced Genomic Files from one or more input Genomic Files which are linked to existing Biospecimens.

2018-11-16 17:19 UTC, dankolbman commented
Still needs more discussion in #475

2018-11-19 15:25 UTC, parimalak commented on dataservice/api/genomic_file/README.md
> +Genomic Files track files related to the bioinformatics process such as `bam`
missing `,`

2018-11-19 17:07 UTC, parimalak approved these changes

2018-11-19 17:18 UTC, znatty22 requested changes
Need more discussion on #475

2019-01-10 16:50 UTC, baileyckelly commented
Per Allison - this is still valid and needs to be done. Moving to backlog as will not be tackled this sprint.

2019-11-04 00:51 UTC, closed without merging