:sparkles: Add ERD generator
kids-first/kf-api-dataservice pull request #61
Opened 2018-01-22 03:42 UTC by dankolbman

Generates an erd from the current definition of the schema.

2018-01-22 03:50 UTC, dankolbman commented on dev-requirements.txt
> +-e git+git@github.com:dankolbman/eralchemy.git@1058c12b828013144f861cb59f0e2c280a1a5ef6#egg=eralchemy
Waiting for [this](https://github.com/Alexis-benoist/eralchemy/pull/42) to merge.

2018-01-22 16:12 UTC, znatty22 requested changes
This is pretty cool 👍,  Only comment is that it looks like File is getting rendered because its in dataservice.api.common.models. Maybe we should remove that since it'll go into its own package later

2018-01-22 16:50 UTC, dankolbman commented
Technically accurate to have File in there. As to whether that ever should have been commited is another question...

2018-01-22 18:16 UTC, znatty22 approved these changes

2018-01-29 01:38 UTC, dankolbman commented on dev-requirements.txt
> +-e git+git@github.com:Alexis-benoist/eralchemy.git#egg=eralchemy
Will want to change this to track the pypy package once a release has been cut.

2018-01-29 18:17 UTC, parimalak approved these changes

2018-01-29 18:22 UTC, merged