📝 point documentation at the kidsfirstdrc.org domain, not kids-first.io
kids-first/kf-api-dataservice pull request #614
Opened 2023-05-16 18:30 UTC by chris-s-friedman

The documentation pointed to kids-first.io. Update that documentation to reference kidsfirstdrc.org

2023-05-16 18:43 UTC, calkinsh approved these changes

2023-05-16 18:55 UTC, znatty22 requested changes
I'm wondering why all of the urls are referring to the QA deployment. Probably should be prod? So can just remove the `-qa` from `https://kf-api-dataservice`

2023-06-21 15:12 UTC, chris-s-friedman commented
@znatty22 unless you feel particularly strong about it, I'm leaving the two commits separate. I see them logically separately : 

1. [2cd3437](https://github.com/kids-first/kf-api-dataservice/pull/614/commits/2cd3437505266120059925357192f839a2d92b9f) to fix the documentation to use the correct domain
2. [1e3f627](https://github.com/kids-first/kf-api-dataservice/pull/614/commits/1e3f627eaf40d5629c858226ff90e4456085087d) change the documentation to reference prod instead of qa

2023-06-21 19:41 UTC, znatty22 approved these changes
Just need to rebase on master, and then its good to go

2023-06-21 20:22 UTC, merged