✨ Store ACL in new authz field
kids-first/kf-api-dataservice pull request #624
Opened 2023-06-13 19:54 UTC by znatty22

2023-06-30 15:31 UTC, chris-s-friedman requested changes
Looks great, Natasha! Besides my one comment, the other thing I'd want to see is a notice in the swagger docs that the acl field is deprecated. When consulting the docs, users should see a warning that if they try to register something with a value in the acl field, they will get a 400 error.

2023-06-30 15:31 UTC, chris-s-friedman commented on dataservice/extensions/flask_indexd.py
> +    def _update_all_acls(self, record, key="acl"):
1. if we're keeping the default for `key` to be "acl" for backwards compatibility and going forward, `authz` should be used, can you document that in the docstring for this function, that the expectation is to use `authz` unless there is some particular reason why "acl" should be used. 
2. If we are deprecating acl, we should change the name of this function to represent that change. If the worry is backwards compatibility, but going forward `"authz"` should be the `key` value used, perhaps we rename this function but add a pointer with the old function name, i.e.:

```python
    def _update_all_access_things(self, record, key='authz'):
        """
        update key field's values for all previous versions of a record and
        update the target record's rev. 
        """
    ...


    def _update_all_acls(self, record):
        """
        Update acls for all previous versions of a record and
        update the target record's rev. Pointer to 
        _update_all_access_things for backwards compatibility
        """
        self._update_all_access_things(record = record, key="acl")
```

2023-07-05 16:30 UTC, znatty22 commented
@chris-s-friedman The best I could do to document the ACL field deprecation in the API docs is:

<img width="955" alt="image" src="https://github.com/kids-first/kf-api-dataservice/assets/10283712/8752eaa3-51b7-4353-a965-83dc697665a5">

Unfortunately the swagger generation lib has changed too much for me to find the old version of the docs and figure out how to annotate the deprecation on the actual schema definition for POSTing genomic files :(

2023-07-05 17:52 UTC, chris-s-friedman approved these changes
Looks great!

2023-09-07 21:54 UTC, merged